### PR TITLE
Update index.js (Not all modules loaded)

### PR DESCRIPTION
**Pull request by c-baeumer**
Hi,

I´ve created this pull request corresponding to [Issue #2](https://github.com/tunnckoCore/load-deps/issues/2).

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Good catch. But can you just change `i` to `-1` please.
You also can write a test for this case, but it's not a problem if you don't.

Thanks!

**Comment by tunnckoCore** [comment]
Okey, test not needed. It's strange, because most of the tests assert the length and it seems it works as expected and loading all modules correctly, hah.

**Comment by c-baeumer** [comment]
I think it depends on the name pattern. 

The length of the resulting object is right, because even, if the indices are wrong, there is an undefined object which is added to the results, if the pattern matches undefined (i.e. Assuming 2 modules and a pattern, which is defined as `*`: `i` runs from 1 to 3, `keys[3]` is undefined, but added, because undefined matches the name pattern)

**Comment by tunnckoCore** [comment]
Good point, but I think this test proof everything [test.js#L44-L56](https://github.com/tunnckoCore/load-deps/blob/master/test.js#L44-L56)?

**Comment by tunnckoCore** [comment]
@c-baeumer thanks!

**Pull request closed without merging**
